apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: pcidevices-controller
  namespace: harvester-system
spec:
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  version: "0.3.2"
  chart: harvester-pcidevices-controller
  {{- if and .Addons .Addons.harvester_pcidevices_controller }}
  enabled: {{ .Addons.harvester_pcidevices_controller.Enabled }}
  {{- else }}
  enabled: false
  {{- end }}
  valuesContent: |
    image:
      tag: v0.3.2
    fullnameOverride: harvester-pcidevices-controller