apiVersion: harvesterhci.io/v1beta1
kind: Addon
metadata:
  name: vm-import-controller
  namespace: harvester-system
spec:
  repo: http://harvester-cluster-repo.cattle-system.svc/charts
  version: "0.1.8"
  chart: harvester-vm-import-controller
  {{- if and .Addons .Addons.harvester_vm_import_controller }}
  enabled: {{ .Addons.harvester_vm_import_controller.Enabled }}
  {{- else }}
  enabled: false
  {{- end }}
  valuesContent: |
    image:
      tag: v0.1.8
    fullnameOverride: harvester-vm-import-controller